### ISSUE TITLE
Spaced Usernames on Windows

### ISSUE THREAD

**Issue by floatzeI** [originphp/originphp#44]
I'm trying to run the local development server and I just get this error:

**Warning**: Unknown: failed to open stream: No such file or directory in **Unknown** on line **0**

**Fatal error**: Unknown: Failed opening required 'C:\Users\Test' (include_path='.;C:\Users\Test User\php71\PEAR\pear') in **Unknown** on line **0**

**Comment by jamielsharief** [comment]
Hi. I would like to work with you get to get this working, originally my core focus was just the linux server and docker environment, however i want to make sure the windows stuff works as well. Its likely down to the different directory seperators, and a path that might be hidden somewhere, i just need to know which file is causing this error. Can you give me more info, which page is showing this? Maybe in the logs/development.log file, it will show more information.

**Comment by jamielsharief** [comment]
I would really like to help with this issue, I just need some more info. Please contact.

**Comment by jamielsharief** [comment]
> I'm trying to run the local development server and I just get this error:
> 
> **Warning**: Unknown: failed to open stream: No such file or directory in **Unknown** on line **0**
> 
> **Fatal error**: Unknown: Failed opening required 'C:\Users\Test' (include_path='.;C:\Users\Test User\php71\PEAR\pear') in **Unknown** on line **0**

Can you tell me which file is causing that for you or provide more info.

I have installed on Windows, and it worked for me. I was running like this

php bin\server

**Comment by floatzeI** [comment]
I'm still getting the same error as before, and basically the same thing in the console. My logs are also empty, with only one file in it called "empty". Here's what the console said when I ran `php bin\server`, anyway:

```OriginPHP Development Server
Starting on http://localhost:8000
```
*after visiting localhost*
```[Mon Jun 24 10:12:52 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Mon Jun 24 10:12:52 2019] PHP Fatal error:  Unknown: Failed opening required 'C:\Users\Test' (include_path='.;C:\Users\Test User\php71\PEAR\pear') in Unknown on line 0
[Mon Jun 24 10:12:52 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Mon Jun 24 10:12:52 2019] PHP Fatal error:  Unknown: Failed opening required 'C:\Users\Test' (include_path='.;C:\Users\Test User\php71\PEAR\pear') in Unknown on line 0
[Mon Jun 24 10:12:52 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Mon Jun 24 10:12:52 2019] PHP Fatal error:  Unknown: Failed opening required 'C:\Users\Test' (include_path='.;C:\Users\Test User\php71\PEAR\pear') in Unknown on line 0
```
I had just guessed the space in my name was an issue since it seems like it's trying to require a file but breaking my name in half. I could be wrong though.

**Comment by jamielsharief** [comment]
My mistake, you put in the subject the exact issue. I am sorry for not understanding sooner. I renamed the directory with a space in it and encoutered the same problem.

The issue is caused by the bin/server script.
If you change the command line as follows, this solved the problem for me

$cmd = "php -S localhost:{$port} -t public"

Thank you so much. Please let me know if this fixes it for you. Its a great bug to find.

**Comment by jamielsharief** [comment]
There have been major security fixes over the weekend and so forth. Recreate project to get all changes and updates. I will close this now.

**Comment by jamielsharief** [comment]
Sorry for delay. Can you run composer clear-cache and then composer
create-project

Your initial assessment was correct it was the spaces in the username that
was breaking the command found in bin\server
