### ISSUE TITLE
Can't find file after first migration

### ISSUE THREAD

**Issue by mel-in-a** [originphp/originphp#87]
Hello, 
I've problem on first install. Following the turotial on your website.
This function in working : but the next one generate error !
I'm using laragon

C:\laragon\www\originphp\blog
λ php bin/console generate model Article title:string body:text
[ OK ] C:\laragon\www\originphp\blog/app\Model\Article.php
[ OK ] C:\laragon\www\originphp\blog/tests\TestCase\Model\ArticleTest.php
[ OK ] C:\laragon\www\originphp\blog/tests\Fixture\ArticleFixture.php
[ OK ] C:\laragon\www\originphp\blog/database\migrations\20200504202023CreateArticleTable.php

This is not working : 

Loading C:\laragon\www\originphp\blog/database\migrations.php

Fatal error: Uncaught ErrorException: file_put_contents(\C:\laragon\www\originphp\blog/logs/application.log): failed to open stream: No such file or directory in C:\laragon\www\originphp\blog\vendor\originphp\log\src\Engine\FileEngine.php:57
Stack trace:
#0 [internal function]: Origin\Console\ErrorHandler->errorHandler(2, 'file_put_conten...', 'C:\\laragon\\www\\...', 57, Array)
#1 C:\laragon\www\originphp\blog\vendor\originphp\log\src\Engine\FileEngine.php(57): file_put_contents('\\C:\\laragon\\www...', '[2020-05-04 20:...', 8)
#2 C:\laragon\www\originphp\blog\vendor\originphp\log\src\Engine\BaseEngine.php(146): Origin\Log\Engine\FileEngine->log('error', '[2020-05-04 20:...', Array)
#3 C:\laragon\www\originphp\blog\vendor\originphp\log\src\Log.php(197): Origin\Log\Engine\BaseEngine->error('ErrorException ...', Array)
#4 C:\laragon\www\originphp\blog\vendor\originphp\log\src\Log.php(98): Origin\Log\Log::write('error', 'ErrorException ...', Array)
#5 C:\laragon\www\originphp\blog\vendor\originphp\framework\src\Console\Erro in C:\laragon\www\originphp\blog\vendor\originphp\log\src\Engine\FileEngine.php on line 57

Thanks for your help

**Comment by mel-in-a** [comment]
Everything is fine on live server :-)

**Comment by jamielsharief** [comment]
I belive this is an issue with your Laragon server, probably something to do with permissions, in particular the `logs` folder. Check your permisions are set up correctly for `logs` and `tmp`

**Comment by jamielsharief** [comment]
This was a bug on windows machines in the log package, that has now been fixed.
